import os
os.system ('clear')
os.system ('pkg install bash -y')
os.system ('pkg install python -y')
os.system ('pkg install python2 -y')
os.system ('pkg install python3 -y')
os.system ('pkg install git -y')
os.system ('pkg install wget -y')
os.system ('pkg install clang -y')
os.system ('pkg install zip -y')
os.system ('pkg install unzip -y')
os.system ('pkg install ruby -y')
os.system ('pkg install perl -y')
os.system ('pkg install ruby -y')
os.system ('pkg install tor -y')
os.system ('pkg install openssl -y')
os.system ('pkg install tar -y')
os.system ('pkg install google -y')
os.system ('pkg install java -y')
os.system ('pkg install nmap -y')
os.system ('clear')
exit ()